name: esathi_companion_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.0 # or the latest version available
  connectivity_plus: ^6.1.1
  network_info_plus: ^6.1.2
  permission_handler: ^10.0.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
  - assets/image_checkincheckout_home.png
  - assets/set_location_attendance.png
  - assets/login_bg.png
  - assets/Microsoft_Logo_16px.png
  - assets/Microsoft_Logo_512px.png
